# Here we have an environment variable that is being set to our environment file with our environment variables or our development environment

ENV["SINATRA_ENV"] ||= "development"

require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "rake console"
task :console do
    Pry.start
end